### ISSUE TITLE
Float window above fullscreen windows?

### ISSUE THREAD

**Issue by themightyoarfish** [filipeisho/breathe#2]
It would be very useful to have the window be always present, even when focused on a fullscreen app. Currently, fullscreen cannot be used at the same time with this app.

What would need to be done to enable this?

**Comment by tryhardfifi** [comment]
Thanks for pointing this out! I also used fullscreen mode a lot but stopped because of breathe... I am not sure how to make the window stay on top even when it's on fullscreen mode. I had two solutions for this problem (not nearly as nice) that were having breathe on the touch bar and/or on the status bar. I know it is not the same but do you think it will work for you while we figure it out?

**Comment by themightyoarfish** [comment]
Would the indicator even be visible peripherally in those locations? I don't think so.
I'm trying to think of an app that does what we want, I'll check back if I think of any. Pretty sure I've seen it done, so there's gotta be a way.

**Comment by tryhardfifi** [comment]
Hello again! Just to let you know I found a way to keep the window above in a full screen app and to even transport it when you switch to another full screen. It's going into the next release 🚀

**Comment by tryhardfifi** [comment]
Hi! The new release is already available, and this feature is implemented, I hope you like it!
